/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.proposta.routines;


import javax.annotation.Generated;

import joindb.jooq.proposta.Proposta;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getanimalidade extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -92475908;

    /**
     * The parameter <code>proposta.getanimalidade.attributeDescription</code>.
     */
    public static final Parameter<String> ATTRIBUTEDESCRIPTION = createParameter("attributeDescription", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.animalType</code>.
     */
    public static final Parameter<String> ANIMALTYPE = createParameter("animalType", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.macho_6</code>.
     */
    public static final Parameter<Integer> MACHO_6 = createParameter("macho_6", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.macho_12</code>.
     */
    public static final Parameter<Integer> MACHO_12 = createParameter("macho_12", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.macho_24</code>.
     */
    public static final Parameter<Integer> MACHO_24 = createParameter("macho_24", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.macho_36</code>.
     */
    public static final Parameter<Integer> MACHO_36 = createParameter("macho_36", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.macho_mais</code>.
     */
    public static final Parameter<Integer> MACHO_MAIS = createParameter("macho_mais", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.femea_6</code>.
     */
    public static final Parameter<Integer> FEMEA_6 = createParameter("femea_6", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.femea_12</code>.
     */
    public static final Parameter<Integer> FEMEA_12 = createParameter("femea_12", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.femea_24</code>.
     */
    public static final Parameter<Integer> FEMEA_24 = createParameter("femea_24", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.femea_36</code>.
     */
    public static final Parameter<Integer> FEMEA_36 = createParameter("femea_36", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proposta.getanimalidade.femea_mais</code>.
     */
    public static final Parameter<Integer> FEMEA_MAIS = createParameter("femea_mais", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Getanimalidade() {
        super("getanimalidade", Proposta.PROPOSTA);

        addInParameter(ATTRIBUTEDESCRIPTION);
        addInParameter(ANIMALTYPE);
        addOutParameter(MACHO_6);
        addOutParameter(MACHO_12);
        addOutParameter(MACHO_24);
        addOutParameter(MACHO_36);
        addOutParameter(MACHO_MAIS);
        addOutParameter(FEMEA_6);
        addOutParameter(FEMEA_12);
        addOutParameter(FEMEA_24);
        addOutParameter(FEMEA_36);
        addOutParameter(FEMEA_MAIS);
    }

    /**
     * Set the <code>attributeDescription</code> parameter IN value to the routine
     */
    public void setAttributedescription(String value) {
        setValue(ATTRIBUTEDESCRIPTION, value);
    }

    /**
     * Set the <code>animalType</code> parameter IN value to the routine
     */
    public void setAnimaltype(String value) {
        setValue(ANIMALTYPE, value);
    }

    /**
     * Get the <code>macho_6</code> parameter OUT value from the routine
     */
    public Integer getMacho_6() {
        return get(MACHO_6);
    }

    /**
     * Get the <code>macho_12</code> parameter OUT value from the routine
     */
    public Integer getMacho_12() {
        return get(MACHO_12);
    }

    /**
     * Get the <code>macho_24</code> parameter OUT value from the routine
     */
    public Integer getMacho_24() {
        return get(MACHO_24);
    }

    /**
     * Get the <code>macho_36</code> parameter OUT value from the routine
     */
    public Integer getMacho_36() {
        return get(MACHO_36);
    }

    /**
     * Get the <code>macho_mais</code> parameter OUT value from the routine
     */
    public Integer getMachoMais() {
        return get(MACHO_MAIS);
    }

    /**
     * Get the <code>femea_6</code> parameter OUT value from the routine
     */
    public Integer getFemea_6() {
        return get(FEMEA_6);
    }

    /**
     * Get the <code>femea_12</code> parameter OUT value from the routine
     */
    public Integer getFemea_12() {
        return get(FEMEA_12);
    }

    /**
     * Get the <code>femea_24</code> parameter OUT value from the routine
     */
    public Integer getFemea_24() {
        return get(FEMEA_24);
    }

    /**
     * Get the <code>femea_36</code> parameter OUT value from the routine
     */
    public Integer getFemea_36() {
        return get(FEMEA_36);
    }

    /**
     * Get the <code>femea_mais</code> parameter OUT value from the routine
     */
    public Integer getFemeaMais() {
        return get(FEMEA_MAIS);
    }
}
