/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.proposta.routines;


import javax.annotation.Generated;

import joindb.jooq.proposta.Proposta;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getequality extends AbstractRoutine<Float> {

    private static final long serialVersionUID = 493380806;

    /**
     * The parameter <code>proposta.getequality.RETURN_VALUE</code>.
     */
    public static final Parameter<Float> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.REAL, false, false);

    /**
     * The parameter <code>proposta.getequality.text1</code>.
     */
    public static final Parameter<String> TEXT1 = createParameter("text1", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>proposta.getequality.text2</code>.
     */
    public static final Parameter<String> TEXT2 = createParameter("text2", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public Getequality() {
        super("getequality", Proposta.PROPOSTA, org.jooq.impl.SQLDataType.REAL);

        setReturnParameter(RETURN_VALUE);
        addInParameter(TEXT1);
        addInParameter(TEXT2);
    }

    /**
     * Set the <code>text1</code> parameter IN value to the routine
     */
    public void setText1(String value) {
        setValue(TEXT1, value);
    }

    /**
     * Set the <code>text1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setText1(Field<String> field) {
        setField(TEXT1, field);
    }

    /**
     * Set the <code>text2</code> parameter IN value to the routine
     */
    public void setText2(String value) {
        setValue(TEXT2, value);
    }

    /**
     * Set the <code>text2</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setText2(Field<String> field) {
        setField(TEXT2, field);
    }
}
