/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.proposta.routines;


import javax.annotation.Generated;

import joindb.jooq.proposta.Proposta;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getinfocodimovel extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 106071339;

    /**
     * The parameter <code>proposta.getinfocodimovel.codigoImovel</code>.
     */
    public static final Parameter<String> CODIGOIMOVEL = createParameter("codigoImovel", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>proposta.getinfocodimovel.siglaEstado</code>.
     */
    public static final Parameter<String> SIGLAESTADO = createParameter("siglaEstado", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>proposta.getinfocodimovel.geocodigoMunicipio</code>.
     */
    public static final Parameter<Integer> GEOCODIGOMUNICIPIO = createParameter("geocodigoMunicipio", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>proposta.getinfocodimovel.idPropriedade</code>.
     */
    public static final Parameter<String> IDPROPRIEDADE = createParameter("idPropriedade", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public Getinfocodimovel() {
        super("getinfocodimovel", Proposta.PROPOSTA);

        addInParameter(CODIGOIMOVEL);
        addOutParameter(SIGLAESTADO);
        addOutParameter(GEOCODIGOMUNICIPIO);
        addOutParameter(IDPROPRIEDADE);
    }

    /**
     * Set the <code>codigoImovel</code> parameter IN value to the routine
     */
    public void setCodigoimovel(String value) {
        setValue(CODIGOIMOVEL, value);
    }

    /**
     * Get the <code>siglaEstado</code> parameter OUT value from the routine
     */
    public String getSiglaestado() {
        return get(SIGLAESTADO);
    }

    /**
     * Get the <code>geocodigoMunicipio</code> parameter OUT value from the routine
     */
    public Integer getGeocodigomunicipio() {
        return get(GEOCODIGOMUNICIPIO);
    }

    /**
     * Get the <code>idPropriedade</code> parameter OUT value from the routine
     */
    public String getIdpropriedade() {
        return get(IDPROPRIEDADE);
    }
}
