/*
 * This file is generated by jOOQ.
 */
package joindb.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import joindb.jooq.csr_database.CsrDatabase;
import joindb.jooq.fbds.Fbds;
import joindb.jooq.gta.Gta;
import joindb.jooq.lt_model.LtModel;
import joindb.jooq.proposta.Proposta;
import joindb.jooq.public_.Public;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 633208001;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>FBDS</code>.
     */
    public final Fbds FBDS = joindb.jooq.fbds.Fbds.FBDS;

    /**
     * The schema <code>csr_database</code>.
     */
    public final CsrDatabase CSR_DATABASE = joindb.jooq.csr_database.CsrDatabase.CSR_DATABASE;

    /**
     * The schema <code>gta</code>.
     */
    public final Gta GTA = joindb.jooq.gta.Gta.GTA;

    /**
     * The schema <code>lt_model</code>.
     */
    public final LtModel LT_MODEL = joindb.jooq.lt_model.LtModel.LT_MODEL;

    /**
     * The schema <code>proposta</code>.
     */
    public final Proposta PROPOSTA = joindb.jooq.proposta.Proposta.PROPOSTA;

    /**
     * The schema <code>public</code>.
     */
    public final Public PUBLIC = joindb.jooq.public_.Public.PUBLIC;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(
            Fbds.FBDS,
            CsrDatabase.CSR_DATABASE,
            Gta.GTA,
            LtModel.LT_MODEL,
            Proposta.PROPOSTA,
            Public.PUBLIC);
    }
}
