/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.fbds.tables.records;


import javax.annotation.Generated;

import joindb.jooq.fbds.tables.AreaImovelMgEs_228Muni;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.postgis.Geometry;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AreaImovelMgEs_228MuniRecord extends UpdatableRecordImpl<AreaImovelMgEs_228MuniRecord> implements Record12<Integer, Geometry, Integer, String, Double, String, String, Double, String, String, String, String> {

    private static final long serialVersionUID = -869098774;

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.id_0</code>.
     */
    public void setId_0(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.id_0</code>.
     */
    public Integer getId_0() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.geom</code>.
     */
    public void setGeom(Geometry value) {
        set(1, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.geom</code>.
     */
    public Geometry getGeom() {
        return (Geometry) get(1);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.id</code>.
     */
    public void setId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.id</code>.
     */
    public Integer getId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.cod_imovel</code>.
     */
    public void setCodImovel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.cod_imovel</code>.
     */
    public String getCodImovel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.num_area</code>.
     */
    public void setNumArea(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.num_area</code>.
     */
    public Double getNumArea() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.cod_estado</code>.
     */
    public void setCodEstado(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.cod_estado</code>.
     */
    public String getCodEstado() {
        return (String) get(5);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.nom_munici</code>.
     */
    public void setNomMunici(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.nom_munici</code>.
     */
    public String getNomMunici() {
        return (String) get(6);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.num_modulo</code>.
     */
    public void setNumModulo(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.num_modulo</code>.
     */
    public Double getNumModulo() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.tipo_imove</code>.
     */
    public void setTipoImove(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.tipo_imove</code>.
     */
    public String getTipoImove() {
        return (String) get(8);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.situacao</code>.
     */
    public void setSituacao(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.situacao</code>.
     */
    public String getSituacao() {
        return (String) get(9);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.condicao_i</code>.
     */
    public void setCondicaoI(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.condicao_i</code>.
     */
    public String getCondicaoI() {
        return (String) get(10);
    }

    /**
     * Setter for <code>FBDS.area_imovel_mg_es_228_muni.geocodigo</code>.
     */
    public void setGeocodigo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>FBDS.area_imovel_mg_es_228_muni.geocodigo</code>.
     */
    public String getGeocodigo() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Geometry, Integer, String, Double, String, String, Double, String, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Geometry, Integer, String, Double, String, String, Double, String, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.ID_0;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Geometry> field2() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.GEOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.COD_IMOVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.NUM_AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.COD_ESTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.NOM_MUNICI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.NUM_MODULO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.TIPO_IMOVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.SITUACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.CONDICAO_I;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.GEOCODIGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId_0();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Geometry component2() {
        return getGeom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCodImovel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getNumArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCodEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNomMunici();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getNumModulo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getTipoImove();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getSituacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCondicaoI();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getGeocodigo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId_0();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Geometry value2() {
        return getGeom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCodImovel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getNumArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCodEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNomMunici();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getNumModulo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getTipoImove();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSituacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCondicaoI();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getGeocodigo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value1(Integer value) {
        setId_0(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value2(Geometry value) {
        setGeom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value3(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value4(String value) {
        setCodImovel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value5(Double value) {
        setNumArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value6(String value) {
        setCodEstado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value7(String value) {
        setNomMunici(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value8(Double value) {
        setNumModulo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value9(String value) {
        setTipoImove(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value10(String value) {
        setSituacao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value11(String value) {
        setCondicaoI(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord value12(String value) {
        setGeocodigo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228MuniRecord values(Integer value1, Geometry value2, Integer value3, String value4, Double value5, String value6, String value7, Double value8, String value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AreaImovelMgEs_228MuniRecord
     */
    public AreaImovelMgEs_228MuniRecord() {
        super(AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI);
    }

    /**
     * Create a detached, initialised AreaImovelMgEs_228MuniRecord
     */
    public AreaImovelMgEs_228MuniRecord(Integer id_0, Geometry geom, Integer id, String codImovel, Double numArea, String codEstado, String nomMunici, Double numModulo, String tipoImove, String situacao, String condicaoI, String geocodigo) {
        super(AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI);

        set(0, id_0);
        set(1, geom);
        set(2, id);
        set(3, codImovel);
        set(4, numArea);
        set(5, codEstado);
        set(6, nomMunici);
        set(7, numModulo);
        set(8, tipoImove);
        set(9, situacao);
        set(10, condicaoI);
        set(11, geocodigo);
    }
}
