/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.lt_model.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import joindb.jooq.lt_model.Indexes;
import joindb.jooq.lt_model.Keys;
import joindb.jooq.lt_model.LtModel;
import joindb.jooq.lt_model.tables.records.ResultRandomRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.postgis.spatial.binding.PostgisGeometryBinding;
import org.postgis.Geometry;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResultRandom extends TableImpl<ResultRandomRecord> {

    private static final long serialVersionUID = -31284171;

    /**
     * The reference instance of <code>lt_model.result_random</code>
     */
    public static final ResultRandom RESULT_RANDOM = new ResultRandom();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResultRandomRecord> getRecordType() {
        return ResultRandomRecord.class;
    }

    /**
     * The column <code>lt_model.result_random.gid</code>.
     */
    public final TableField<ResultRandomRecord, Integer> GID = createField("gid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('lt_model.result_gid_seq3'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>lt_model.result_random.table_source</code>.
     */
    public final TableField<ResultRandomRecord, String> TABLE_SOURCE = createField("table_source", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lt_model.result_random.ownership_class</code>.
     */
    public final TableField<ResultRandomRecord, String> OWNERSHIP_CLASS = createField("ownership_class", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lt_model.result_random.sub_class</code>.
     */
    public final TableField<ResultRandomRecord, String> SUB_CLASS = createField("sub_class", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lt_model.result_random.area_original</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> AREA_ORIGINAL = createField("area_original", org.jooq.impl.SQLDataType.NUMERIC(30, 4), this, "");

    /**
     * The column <code>lt_model.result_random.original_gid</code>.
     */
    public final TableField<ResultRandomRecord, Long> ORIGINAL_GID = createField("original_gid", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>lt_model.result_random.geom</code>.
     */
    public final TableField<ResultRandomRecord, Geometry> GEOM = createField("geom", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "", new PostgisGeometryBinding());

    /**
     * The column <code>lt_model.result_random.area</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> AREA = createField("area", org.jooq.impl.SQLDataType.NUMERIC(30, 4), this, "");

    /**
     * The column <code>lt_model.result_random.ag_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> AG_AREA_LOSS = createField("ag_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.aru_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> ARU_AREA_LOSS = createField("aru_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.carpo_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> CARPO_AREA_LOSS = createField("carpo_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.carpr_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> CARPR_AREA_LOSS = createField("carpr_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.com_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> COM_AREA_LOSS = createField("com_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.ml_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> ML_AREA_LOSS = createField("ml_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.nd_b_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> ND_B_AREA_LOSS = createField("nd_b_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.nd_i_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> ND_I_AREA_LOSS = createField("nd_i_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.ql_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> QL_AREA_LOSS = createField("ql_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.sigef_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> SIGEF_AREA_LOSS = createField("sigef_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.ti_h_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> TI_H_AREA_LOSS = createField("ti_h_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.ti_n_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> TI_N_AREA_LOSS = createField("ti_n_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.tlpc_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> TLPC_AREA_LOSS = createField("tlpc_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.tlpl_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> TLPL_AREA_LOSS = createField("tlpl_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.trans_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> TRANS_AREA_LOSS = createField("trans_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.ucpi_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> UCPI_AREA_LOSS = createField("ucpi_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.ucus_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> UCUS_AREA_LOSS = createField("ucus_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.urb_area_loss</code>.
     */
    public final TableField<ResultRandomRecord, BigDecimal> URB_AREA_LOSS = createField("urb_area_loss", org.jooq.impl.SQLDataType.NUMERIC(30, 2), this, "");

    /**
     * The column <code>lt_model.result_random.cd_mun_2006</code>.
     */
    public final TableField<ResultRandomRecord, Integer> CD_MUN_2006 = createField("cd_mun_2006", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lt_model.result_random.rast</code>.
     */
    public final TableField<ResultRandomRecord, Integer> RAST = createField("rast", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lt_model.result_random.name</code>.
     */
    public final TableField<ResultRandomRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>lt_model.result_random.cd_mun</code>.
     */
    public final TableField<ResultRandomRecord, Integer> CD_MUN = createField("cd_mun", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>lt_model.result_random.cd_mun_contain</code>.
     */
    public final TableField<ResultRandomRecord, Boolean> CD_MUN_CONTAIN = createField("cd_mun_contain", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>lt_model.result_random</code> table reference
     */
    public ResultRandom() {
        this(DSL.name("result_random"), null);
    }

    /**
     * Create an aliased <code>lt_model.result_random</code> table reference
     */
    public ResultRandom(String alias) {
        this(DSL.name(alias), RESULT_RANDOM);
    }

    /**
     * Create an aliased <code>lt_model.result_random</code> table reference
     */
    public ResultRandom(Name alias) {
        this(alias, RESULT_RANDOM);
    }

    private ResultRandom(Name alias, Table<ResultRandomRecord> aliased) {
        this(alias, aliased, null);
    }

    private ResultRandom(Name alias, Table<ResultRandomRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ResultRandom(Table<O> child, ForeignKey<O, ResultRandomRecord> key) {
        super(child, key, RESULT_RANDOM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return LtModel.LT_MODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GIX_RESULT_RANDOM, Indexes.RESULT_PKEY3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ResultRandomRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RESULT_RANDOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ResultRandomRecord> getPrimaryKey() {
        return Keys.RESULT_PKEY3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ResultRandomRecord>> getKeys() {
        return Arrays.<UniqueKey<ResultRandomRecord>>asList(Keys.RESULT_PKEY3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultRandom as(String alias) {
        return new ResultRandom(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ResultRandom as(Name alias) {
        return new ResultRandom(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResultRandom rename(String name) {
        return new ResultRandom(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResultRandom rename(Name name) {
        return new ResultRandom(name, null);
    }
}
