/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.fbds.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import joindb.jooq.fbds.Fbds;
import joindb.jooq.fbds.Indexes;
import joindb.jooq.fbds.Keys;
import joindb.jooq.fbds.tables.records.AreaImovelMgEs_228MuniRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.postgis.spatial.binding.PostgisGeometryBinding;
import org.postgis.Geometry;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AreaImovelMgEs_228Muni extends TableImpl<AreaImovelMgEs_228MuniRecord> {

    private static final long serialVersionUID = 1425396830;

    /**
     * The reference instance of <code>FBDS.area_imovel_mg_es_228_muni</code>
     */
    public static final AreaImovelMgEs_228Muni AREA_IMOVEL_MG_ES_228_MUNI = new AreaImovelMgEs_228Muni();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AreaImovelMgEs_228MuniRecord> getRecordType() {
        return AreaImovelMgEs_228MuniRecord.class;
    }

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.id_0</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, Integer> ID_0 = createField("id_0", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('\"FBDS\".area_imovel_mg_es_228_muni_id_0_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.geom</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, Geometry> GEOM = createField("geom", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "", new PostgisGeometryBinding());

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.id</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.cod_imovel</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, String> COD_IMOVEL = createField("cod_imovel", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.num_area</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, Double> NUM_AREA = createField("num_area", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.cod_estado</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, String> COD_ESTADO = createField("cod_estado", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.nom_munici</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, String> NOM_MUNICI = createField("nom_munici", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.num_modulo</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, Double> NUM_MODULO = createField("num_modulo", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.tipo_imove</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, String> TIPO_IMOVE = createField("tipo_imove", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.situacao</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, String> SITUACAO = createField("situacao", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.condicao_i</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, String> CONDICAO_I = createField("condicao_i", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>FBDS.area_imovel_mg_es_228_muni.geocodigo</code>.
     */
    public final TableField<AreaImovelMgEs_228MuniRecord, String> GEOCODIGO = createField("geocodigo", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * Create a <code>FBDS.area_imovel_mg_es_228_muni</code> table reference
     */
    public AreaImovelMgEs_228Muni() {
        this(DSL.name("area_imovel_mg_es_228_muni"), null);
    }

    /**
     * Create an aliased <code>FBDS.area_imovel_mg_es_228_muni</code> table reference
     */
    public AreaImovelMgEs_228Muni(String alias) {
        this(DSL.name(alias), AREA_IMOVEL_MG_ES_228_MUNI);
    }

    /**
     * Create an aliased <code>FBDS.area_imovel_mg_es_228_muni</code> table reference
     */
    public AreaImovelMgEs_228Muni(Name alias) {
        this(alias, AREA_IMOVEL_MG_ES_228_MUNI);
    }

    private AreaImovelMgEs_228Muni(Name alias, Table<AreaImovelMgEs_228MuniRecord> aliased) {
        this(alias, aliased, null);
    }

    private AreaImovelMgEs_228Muni(Name alias, Table<AreaImovelMgEs_228MuniRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AreaImovelMgEs_228Muni(Table<O> child, ForeignKey<O, AreaImovelMgEs_228MuniRecord> key) {
        super(child, key, AREA_IMOVEL_MG_ES_228_MUNI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Fbds.FBDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AREA_IMOVEL_MG_ES_228_MUNI_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AreaImovelMgEs_228MuniRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AREA_IMOVEL_MG_ES_228_MUNI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AreaImovelMgEs_228MuniRecord> getPrimaryKey() {
        return Keys.AREA_IMOVEL_MG_ES_228_MUNI_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AreaImovelMgEs_228MuniRecord>> getKeys() {
        return Arrays.<UniqueKey<AreaImovelMgEs_228MuniRecord>>asList(Keys.AREA_IMOVEL_MG_ES_228_MUNI_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228Muni as(String alias) {
        return new AreaImovelMgEs_228Muni(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelMgEs_228Muni as(Name alias) {
        return new AreaImovelMgEs_228Muni(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AreaImovelMgEs_228Muni rename(String name) {
        return new AreaImovelMgEs_228Muni(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AreaImovelMgEs_228Muni rename(Name name) {
        return new AreaImovelMgEs_228Muni(name, null);
    }
}
