/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.public_.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import joindb.jooq.public_.Indexes;
import joindb.jooq.public_.Keys;
import joindb.jooq.public_.Public;
import joindb.jooq.public_.tables.records.AreaImovelJuntosRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.postgis.spatial.binding.PostgisGeometryBinding;
import org.postgis.Geometry;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AreaImovelJuntos extends TableImpl<AreaImovelJuntosRecord> {

    private static final long serialVersionUID = -666676358;

    /**
     * The reference instance of <code>public.area_imovel_juntos</code>
     */
    public static final AreaImovelJuntos AREA_IMOVEL_JUNTOS = new AreaImovelJuntos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AreaImovelJuntosRecord> getRecordType() {
        return AreaImovelJuntosRecord.class;
    }

    /**
     * The column <code>public.area_imovel_juntos.id</code>.
     */
    public final TableField<AreaImovelJuntosRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('\"AREA_IMOVEL_juntos_id_seq\"'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.area_imovel_juntos.geom</code>.
     */
    public final TableField<AreaImovelJuntosRecord, Geometry> GEOM = createField("geom", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "", new PostgisGeometryBinding());

    /**
     * The column <code>public.area_imovel_juntos.cod_imovel</code>.
     */
    public final TableField<AreaImovelJuntosRecord, String> COD_IMOVEL = createField("cod_imovel", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>public.area_imovel_juntos.num_area</code>.
     */
    public final TableField<AreaImovelJuntosRecord, BigDecimal> NUM_AREA = createField("num_area", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.area_imovel_juntos.cod_estado</code>.
     */
    public final TableField<AreaImovelJuntosRecord, String> COD_ESTADO = createField("cod_estado", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>public.area_imovel_juntos.nom_munici</code>.
     */
    public final TableField<AreaImovelJuntosRecord, String> NOM_MUNICI = createField("nom_munici", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>public.area_imovel_juntos.num_modulo</code>.
     */
    public final TableField<AreaImovelJuntosRecord, BigDecimal> NUM_MODULO = createField("num_modulo", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.area_imovel_juntos.tipo_imove</code>.
     */
    public final TableField<AreaImovelJuntosRecord, String> TIPO_IMOVE = createField("tipo_imove", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>public.area_imovel_juntos.situacao</code>.
     */
    public final TableField<AreaImovelJuntosRecord, String> SITUACAO = createField("situacao", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>public.area_imovel_juntos.condicao_i</code>.
     */
    public final TableField<AreaImovelJuntosRecord, String> CONDICAO_I = createField("condicao_i", org.jooq.impl.SQLDataType.VARCHAR(85), this, "");

    /**
     * Create a <code>public.area_imovel_juntos</code> table reference
     */
    public AreaImovelJuntos() {
        this(DSL.name("area_imovel_juntos"), null);
    }

    /**
     * Create an aliased <code>public.area_imovel_juntos</code> table reference
     */
    public AreaImovelJuntos(String alias) {
        this(DSL.name(alias), AREA_IMOVEL_JUNTOS);
    }

    /**
     * Create an aliased <code>public.area_imovel_juntos</code> table reference
     */
    public AreaImovelJuntos(Name alias) {
        this(alias, AREA_IMOVEL_JUNTOS);
    }

    private AreaImovelJuntos(Name alias, Table<AreaImovelJuntosRecord> aliased) {
        this(alias, aliased, null);
    }

    private AreaImovelJuntos(Name alias, Table<AreaImovelJuntosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AreaImovelJuntos(Table<O> child, ForeignKey<O, AreaImovelJuntosRecord> key) {
        super(child, key, AREA_IMOVEL_JUNTOS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AREA_IMOVEL_JUNTOS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AreaImovelJuntosRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AREA_IMOVEL_JUNTOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AreaImovelJuntosRecord> getPrimaryKey() {
        return Keys.AREA_IMOVEL_JUNTOS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AreaImovelJuntosRecord>> getKeys() {
        return Arrays.<UniqueKey<AreaImovelJuntosRecord>>asList(Keys.AREA_IMOVEL_JUNTOS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntos as(String alias) {
        return new AreaImovelJuntos(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntos as(Name alias) {
        return new AreaImovelJuntos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AreaImovelJuntos rename(String name) {
        return new AreaImovelJuntos(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AreaImovelJuntos rename(Name name) {
        return new AreaImovelJuntos(name, null);
    }
}
