/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.gta;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import joindb.jooq.DefaultCatalog;
import joindb.jooq.gta.tables.MtTransactions2;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gta extends SchemaImpl {

    private static final long serialVersionUID = -1041889848;

    /**
     * The reference instance of <code>gta</code>
     */
    public static final Gta GTA = new Gta();

    /**
     * The table <code>gta.mt_transactions2</code>.
     */
    public final MtTransactions2 MT_TRANSACTIONS2 = joindb.jooq.gta.tables.MtTransactions2.MT_TRANSACTIONS2;

    /**
     * No further instances allowed
     */
    private Gta() {
        super("gta", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            MtTransactions2.MT_TRANSACTIONS2);
    }
}
