/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.gta;


import javax.annotation.Generated;

import joindb.jooq.gta.tables.MtTransactions2;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>gta</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MT_TRANSACTIONS2_PK = Indexes0.MT_TRANSACTIONS2_PK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index MT_TRANSACTIONS2_PK = Internal.createIndex("mt_transactions2_pk", MtTransactions2.MT_TRANSACTIONS2, new OrderField[] { MtTransactions2.MT_TRANSACTIONS2.SCRAPEID }, true);
    }
}
