/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.gta;


import javax.annotation.Generated;

import joindb.jooq.gta.tables.MtTransactions2;


/**
 * Convenience access to all tables in gta
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>gta.mt_transactions2</code>.
     */
    public static final MtTransactions2 MT_TRANSACTIONS2 = joindb.jooq.gta.tables.MtTransactions2.MT_TRANSACTIONS2;
}
