/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.proposta.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import joindb.jooq.csr_database.tables.Estados;
import joindb.jooq.csr_database.tables.Municipios;
import joindb.jooq.proposta.Indexes;
import joindb.jooq.proposta.Keys;
import joindb.jooq.proposta.Proposta;
import joindb.jooq.proposta.tables.records.GuiaTransitoAnimalRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuiaTransitoAnimal extends TableImpl<GuiaTransitoAnimalRecord> {

    private static final long serialVersionUID = -296513119;

    /**
     * The reference instance of <code>proposta.guia_transito_animal</code>
     */
    public static final GuiaTransitoAnimal GUIA_TRANSITO_ANIMAL = new GuiaTransitoAnimal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuiaTransitoAnimalRecord> getRecordType() {
        return GuiaTransitoAnimalRecord.class;
    }

    /**
     * The column <code>proposta.guia_transito_animal.id</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>proposta.guia_transito_animal.municipio_destino</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> MUNICIPIO_DESTINO = createField("municipio_destino", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.municipio_fonte</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> MUNICIPIO_FONTE = createField("municipio_fonte", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.propriedade_fonte_id</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> PROPRIEDADE_FONTE_ID = createField("propriedade_fonte_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.propriedade_destino_id</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> PROPRIEDADE_DESTINO_ID = createField("propriedade_destino_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.estado_fonte</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> ESTADO_FONTE = createField("estado_fonte", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.estado_destino</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> ESTADO_DESTINO = createField("estado_destino", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.transporte_id</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, String> TRANSPORTE_ID = createField("transporte_id", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>proposta.guia_transito_animal.especie_tipo</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, String> ESPECIE_TIPO = createField("especie_tipo", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>proposta.guia_transito_animal.transporte_motivo</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, String> TRANSPORTE_MOTIVO = createField("transporte_motivo", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>proposta.guia_transito_animal.meio_transporte</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, String> MEIO_TRANSPORTE = createField("meio_transporte", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>proposta.guia_transito_animal.data_emitida</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Date> DATA_EMITIDA = createField("data_emitida", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.vacina_aftosa_primeira</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Date> VACINA_AFTOSA_PRIMEIRA = createField("vacina_aftosa_primeira", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.vacina_aftosa_segunda</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Date> VACINA_AFTOSA_SEGUNDA = createField("vacina_aftosa_segunda", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.vacina_bucellosis</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Date> VACINA_BUCELLOSIS = createField("vacina_bucellosis", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.vacina_merek</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Date> VACINA_MEREK = createField("vacina_merek", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.emissor_id</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, String> EMISSOR_ID = createField("emissor_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.emissao_tipo</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, String> EMISSAO_TIPO = createField("emissao_tipo", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>proposta.guia_transito_animal.valido_ate</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Date> VALIDO_ATE = createField("valido_ate", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.situacao</code>. Situação do GTA: BAIXADA
     */
    public final TableField<GuiaTransitoAnimalRecord, String> SITUACAO = createField("situacao", org.jooq.impl.SQLDataType.VARCHAR, this, "Situação do GTA: BAIXADA");

    /**
     * The column <code>proposta.guia_transito_animal.femea_6</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> FEMEA_6 = createField("femea_6", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.femea_12</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> FEMEA_12 = createField("femea_12", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.femea_24</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> FEMEA_24 = createField("femea_24", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.femea_36</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> FEMEA_36 = createField("femea_36", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.femea_mais</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> FEMEA_MAIS = createField("femea_mais", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.macho_6</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> MACHO_6 = createField("macho_6", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.macho_12</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> MACHO_12 = createField("macho_12", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.macho_24</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> MACHO_24 = createField("macho_24", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.macho_36</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> MACHO_36 = createField("macho_36", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>proposta.guia_transito_animal.macho_mais</code>.
     */
    public final TableField<GuiaTransitoAnimalRecord, Integer> MACHO_MAIS = createField("macho_mais", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>proposta.guia_transito_animal</code> table reference
     */
    public GuiaTransitoAnimal() {
        this(DSL.name("guia_transito_animal"), null);
    }

    /**
     * Create an aliased <code>proposta.guia_transito_animal</code> table reference
     */
    public GuiaTransitoAnimal(String alias) {
        this(DSL.name(alias), GUIA_TRANSITO_ANIMAL);
    }

    /**
     * Create an aliased <code>proposta.guia_transito_animal</code> table reference
     */
    public GuiaTransitoAnimal(Name alias) {
        this(alias, GUIA_TRANSITO_ANIMAL);
    }

    private GuiaTransitoAnimal(Name alias, Table<GuiaTransitoAnimalRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuiaTransitoAnimal(Name alias, Table<GuiaTransitoAnimalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GuiaTransitoAnimal(Table<O> child, ForeignKey<O, GuiaTransitoAnimalRecord> key) {
        super(child, key, GUIA_TRANSITO_ANIMAL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proposta.PROPOSTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GTA_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GuiaTransitoAnimalRecord> getPrimaryKey() {
        return Keys.GTA_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GuiaTransitoAnimalRecord>> getKeys() {
        return Arrays.<UniqueKey<GuiaTransitoAnimalRecord>>asList(Keys.GTA_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GuiaTransitoAnimalRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GuiaTransitoAnimalRecord, ?>>asList(Keys.GUIA_TRANSITO_ANIMAL__FK_GTA_MUNICIPIO_DESTINO_ID, Keys.GUIA_TRANSITO_ANIMAL__FK_GTA_MUNICIPIO_FONTE_ID, Keys.GUIA_TRANSITO_ANIMAL__FK_GTA_ESTADOS_FONTE_ID, Keys.GUIA_TRANSITO_ANIMAL__FK_GTA_ESTADOS_DESTINO_ID);
    }

    public Municipios guiaTransitoAnimal_FkGtaMunicipioDestinoId() {
        return new Municipios(this, Keys.GUIA_TRANSITO_ANIMAL__FK_GTA_MUNICIPIO_DESTINO_ID);
    }

    public Municipios guiaTransitoAnimal_FkGtaMunicipioFonteId() {
        return new Municipios(this, Keys.GUIA_TRANSITO_ANIMAL__FK_GTA_MUNICIPIO_FONTE_ID);
    }

    public Estados guiaTransitoAnimal_FkGtaEstadosFonteId() {
        return new Estados(this, Keys.GUIA_TRANSITO_ANIMAL__FK_GTA_ESTADOS_FONTE_ID);
    }

    public Estados guiaTransitoAnimal_FkGtaEstadosDestinoId() {
        return new Estados(this, Keys.GUIA_TRANSITO_ANIMAL__FK_GTA_ESTADOS_DESTINO_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuiaTransitoAnimal as(String alias) {
        return new GuiaTransitoAnimal(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuiaTransitoAnimal as(Name alias) {
        return new GuiaTransitoAnimal(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuiaTransitoAnimal rename(String name) {
        return new GuiaTransitoAnimal(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuiaTransitoAnimal rename(Name name) {
        return new GuiaTransitoAnimal(name, null);
    }
}
