/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.proposta.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import joindb.jooq.proposta.tables.Propriedade;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.postgis.Geometry;


/**
 * Armazena a propriedade em uma determinada data
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropriedadeRecord extends UpdatableRecordImpl<PropriedadeRecord> implements Record7<Integer, Date, Integer, Integer, String, Geometry, BigDecimal> {

    private static final long serialVersionUID = 263914014;

    /**
     * Setter for <code>proposta.propriedade.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proposta.propriedade.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proposta.propriedade.data</code>.
     */
    public void setData(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>proposta.propriedade.data</code>.
     */
    public Date getData() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>proposta.propriedade.estado_id</code>.
     */
    public void setEstadoId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proposta.propriedade.estado_id</code>.
     */
    public Integer getEstadoId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proposta.propriedade.municipio_id</code>.
     */
    public void setMunicipioId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>proposta.propriedade.municipio_id</code>.
     */
    public Integer getMunicipioId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>proposta.propriedade.abatedouro</code>.
     */
    public void setAbatedouro(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>proposta.propriedade.abatedouro</code>.
     */
    public String getAbatedouro() {
        return (String) get(4);
    }

    /**
     * Setter for <code>proposta.propriedade.geom</code>.
     */
    public void setGeom(Geometry value) {
        set(5, value);
    }

    /**
     * Getter for <code>proposta.propriedade.geom</code>.
     */
    public Geometry getGeom() {
        return (Geometry) get(5);
    }

    /**
     * Setter for <code>proposta.propriedade.area</code>.
     */
    public void setArea(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>proposta.propriedade.area</code>.
     */
    public BigDecimal getArea() {
        return (BigDecimal) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Date, Integer, Integer, String, Geometry, BigDecimal> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Date, Integer, Integer, String, Geometry, BigDecimal> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Propriedade.PROPRIEDADE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return Propriedade.PROPRIEDADE.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Propriedade.PROPRIEDADE.ESTADO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Propriedade.PROPRIEDADE.MUNICIPIO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Propriedade.PROPRIEDADE.ABATEDOURO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Geometry> field6() {
        return Propriedade.PROPRIEDADE.GEOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return Propriedade.PROPRIEDADE.AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getEstadoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getMunicipioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAbatedouro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Geometry component6() {
        return getGeom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEstadoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMunicipioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAbatedouro();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Geometry value6() {
        return getGeom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeRecord value2(Date value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeRecord value3(Integer value) {
        setEstadoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeRecord value4(Integer value) {
        setMunicipioId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeRecord value5(String value) {
        setAbatedouro(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeRecord value6(Geometry value) {
        setGeom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeRecord value7(BigDecimal value) {
        setArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeRecord values(Integer value1, Date value2, Integer value3, Integer value4, String value5, Geometry value6, BigDecimal value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PropriedadeRecord
     */
    public PropriedadeRecord() {
        super(Propriedade.PROPRIEDADE);
    }

    /**
     * Create a detached, initialised PropriedadeRecord
     */
    public PropriedadeRecord(Integer id, Date data, Integer estadoId, Integer municipioId, String abatedouro, Geometry geom, BigDecimal area) {
        super(Propriedade.PROPRIEDADE);

        set(0, id);
        set(1, data);
        set(2, estadoId);
        set(3, municipioId);
        set(4, abatedouro);
        set(5, geom);
        set(6, area);
    }
}
