/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.proposta.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import joindb.jooq.proposta.tables.PropriedadeInformacao;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropriedadeInformacaoRecord extends UpdatableRecordImpl<PropriedadeInformacaoRecord> implements Record12<Integer, Integer, Integer, Integer, Long, String, Long, String, Long, String, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 968117077;

    /**
     * Setter for <code>proposta.propriedade_informacao.id</code>. identificador unico da propriedade
O mesmo car pode ser usado para duas propriedades diferentes.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.id</code>. identificador unico da propriedade
O mesmo car pode ser usado para duas propriedades diferentes.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.estado_id</code>.
     */
    public void setEstadoId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.estado_id</code>.
     */
    public Integer getEstadoId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.municipio_id</code>.
     */
    public void setMunicipioId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.municipio_id</code>.
     */
    public Integer getMunicipioId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.propriedade_id</code>.
     */
    public void setPropriedadeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.propriedade_id</code>.
     */
    public Integer getPropriedadeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.cnpj</code>.
     */
    public void setCnpj(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.cnpj</code>.
     */
    public Long getCnpj() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.nome_propriedade</code>.
     */
    public void setNomePropriedade(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.nome_propriedade</code>.
     */
    public String getNomePropriedade() {
        return (String) get(5);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.cpf</code>.
     */
    public void setCpf(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.cpf</code>.
     */
    public Long getCpf() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.nome_proprietario</code>.
     */
    public void setNomeProprietario(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.nome_proprietario</code>.
     */
    public String getNomeProprietario() {
        return (String) get(7);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.empreendimento_id</code>.
     */
    public void setEmpreendimentoId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.empreendimento_id</code>.
     */
    public Long getEmpreendimentoId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.codigo_imovel</code>.
     */
    public void setCodigoImovel(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.codigo_imovel</code>.
     */
    public String getCodigoImovel() {
        return (String) get(9);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.modulo_count</code>.
     */
    public void setModuloCount(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.modulo_count</code>.
     */
    public BigDecimal getModuloCount() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>proposta.propriedade_informacao.area</code>.
     */
    public void setArea(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>proposta.propriedade_informacao.area</code>.
     */
    public BigDecimal getArea() {
        return (BigDecimal) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Integer, Long, String, Long, String, Long, String, BigDecimal, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Integer, Long, String, Long, String, Long, String, BigDecimal, BigDecimal> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.ESTADO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.MUNICIPIO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.PROPRIEDADE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.CNPJ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.NOME_PROPRIEDADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.CPF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.NOME_PROPRIETARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.EMPREENDIMENTO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.CODIGO_IMOVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.MODULO_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return PropriedadeInformacao.PROPRIEDADE_INFORMACAO.AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getEstadoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMunicipioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPropriedadeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getCnpj();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNomePropriedade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getCpf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getNomeProprietario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getEmpreendimentoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCodigoImovel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getModuloCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEstadoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMunicipioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPropriedadeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getCnpj();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNomePropriedade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getCpf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNomeProprietario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getEmpreendimentoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCodigoImovel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getModuloCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value2(Integer value) {
        setEstadoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value3(Integer value) {
        setMunicipioId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value4(Integer value) {
        setPropriedadeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value5(Long value) {
        setCnpj(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value6(String value) {
        setNomePropriedade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value7(Long value) {
        setCpf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value8(String value) {
        setNomeProprietario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value9(Long value) {
        setEmpreendimentoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value10(String value) {
        setCodigoImovel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value11(BigDecimal value) {
        setModuloCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord value12(BigDecimal value) {
        setArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropriedadeInformacaoRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Long value5, String value6, Long value7, String value8, Long value9, String value10, BigDecimal value11, BigDecimal value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PropriedadeInformacaoRecord
     */
    public PropriedadeInformacaoRecord() {
        super(PropriedadeInformacao.PROPRIEDADE_INFORMACAO);
    }

    /**
     * Create a detached, initialised PropriedadeInformacaoRecord
     */
    public PropriedadeInformacaoRecord(Integer id, Integer estadoId, Integer municipioId, Integer propriedadeId, Long cnpj, String nomePropriedade, Long cpf, String nomeProprietario, Long empreendimentoId, String codigoImovel, BigDecimal moduloCount, BigDecimal area) {
        super(PropriedadeInformacao.PROPRIEDADE_INFORMACAO);

        set(0, id);
        set(1, estadoId);
        set(2, municipioId);
        set(3, propriedadeId);
        set(4, cnpj);
        set(5, nomePropriedade);
        set(6, cpf);
        set(7, nomeProprietario);
        set(8, empreendimentoId);
        set(9, codigoImovel);
        set(10, moduloCount);
        set(11, area);
    }
}
