/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.csr_database.tables;


import javax.annotation.Generated;

import joindb.jooq.csr_database.CsrDatabase;
import joindb.jooq.csr_database.tables.records.MtMunicipioRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MtMunicipio extends TableImpl<MtMunicipioRecord> {

    private static final long serialVersionUID = 1376586793;

    /**
     * The reference instance of <code>csr_database.mt_municipio</code>
     */
    public static final MtMunicipio MT_MUNICIPIO = new MtMunicipio();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MtMunicipioRecord> getRecordType() {
        return MtMunicipioRecord.class;
    }

    /**
     * The column <code>csr_database.mt_municipio.estado_id</code>.
     */
    public final TableField<MtMunicipioRecord, Integer> ESTADO_ID = createField("estado_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>csr_database.mt_municipio.estado_sigla</code>.
     */
    public final TableField<MtMunicipioRecord, String> ESTADO_SIGLA = createField("estado_sigla", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>csr_database.mt_municipio.municipio_id</code>.
     */
    public final TableField<MtMunicipioRecord, Integer> MUNICIPIO_ID = createField("municipio_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>csr_database.mt_municipio.municipio_geocodigo</code>.
     */
    public final TableField<MtMunicipioRecord, Integer> MUNICIPIO_GEOCODIGO = createField("municipio_geocodigo", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>csr_database.mt_municipio</code> table reference
     */
    public MtMunicipio() {
        this(DSL.name("mt_municipio"), null);
    }

    /**
     * Create an aliased <code>csr_database.mt_municipio</code> table reference
     */
    public MtMunicipio(String alias) {
        this(DSL.name(alias), MT_MUNICIPIO);
    }

    /**
     * Create an aliased <code>csr_database.mt_municipio</code> table reference
     */
    public MtMunicipio(Name alias) {
        this(alias, MT_MUNICIPIO);
    }

    private MtMunicipio(Name alias, Table<MtMunicipioRecord> aliased) {
        this(alias, aliased, null);
    }

    private MtMunicipio(Name alias, Table<MtMunicipioRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> MtMunicipio(Table<O> child, ForeignKey<O, MtMunicipioRecord> key) {
        super(child, key, MT_MUNICIPIO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CsrDatabase.CSR_DATABASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MtMunicipio as(String alias) {
        return new MtMunicipio(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MtMunicipio as(Name alias) {
        return new MtMunicipio(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MtMunicipio rename(String name) {
        return new MtMunicipio(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MtMunicipio rename(Name name) {
        return new MtMunicipio(name, null);
    }
}
