/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.csr_database.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import joindb.jooq.csr_database.CsrDatabase;
import joindb.jooq.csr_database.Indexes;
import joindb.jooq.csr_database.Keys;
import joindb.jooq.csr_database.tables.records.MunicipiosRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.postgis.spatial.binding.PostgisGeometryBinding;
import org.postgis.Geometry;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Municipios extends TableImpl<MunicipiosRecord> {

    private static final long serialVersionUID = -636513715;

    /**
     * The reference instance of <code>csr_database.municipios</code>
     */
    public static final Municipios MUNICIPIOS = new Municipios();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MunicipiosRecord> getRecordType() {
        return MunicipiosRecord.class;
    }

    /**
     * The column <code>csr_database.municipios.id</code>.
     */
    public final TableField<MunicipiosRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('csr_database.municipios_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>csr_database.municipios.geom</code>.
     */
    public final TableField<MunicipiosRecord, Geometry> GEOM = createField("geom", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), this, "", new PostgisGeometryBinding());

    /**
     * The column <code>csr_database.municipios.nome</code>.
     */
    public final TableField<MunicipiosRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>csr_database.municipios.geocodigo</code>.
     */
    public final TableField<MunicipiosRecord, Integer> GEOCODIGO = createField("geocodigo", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>csr_database.municipios</code> table reference
     */
    public Municipios() {
        this(DSL.name("municipios"), null);
    }

    /**
     * Create an aliased <code>csr_database.municipios</code> table reference
     */
    public Municipios(String alias) {
        this(DSL.name(alias), MUNICIPIOS);
    }

    /**
     * Create an aliased <code>csr_database.municipios</code> table reference
     */
    public Municipios(Name alias) {
        this(alias, MUNICIPIOS);
    }

    private Municipios(Name alias, Table<MunicipiosRecord> aliased) {
        this(alias, aliased, null);
    }

    private Municipios(Name alias, Table<MunicipiosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Municipios(Table<O> child, ForeignKey<O, MunicipiosRecord> key) {
        super(child, key, MUNICIPIOS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CsrDatabase.CSR_DATABASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MUNICIPIOS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MunicipiosRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MUNICIPIOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MunicipiosRecord> getPrimaryKey() {
        return Keys.MUNICIPIOS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MunicipiosRecord>> getKeys() {
        return Arrays.<UniqueKey<MunicipiosRecord>>asList(Keys.MUNICIPIOS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Municipios as(String alias) {
        return new Municipios(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Municipios as(Name alias) {
        return new Municipios(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Municipios rename(String name) {
        return new Municipios(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Municipios rename(Name name) {
        return new Municipios(name, null);
    }
}
