/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.public_;


import javax.annotation.Generated;

import joindb.jooq.public_.tables.AreaImovelJuntos;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AREA_IMOVEL_JUNTOS_PKEY = Indexes0.AREA_IMOVEL_JUNTOS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AREA_IMOVEL_JUNTOS_PKEY = Internal.createIndex("AREA_IMOVEL_juntos_pkey", AreaImovelJuntos.AREA_IMOVEL_JUNTOS, new OrderField[] { AreaImovelJuntos.AREA_IMOVEL_JUNTOS.ID }, true);
    }
}
