/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.public_;


import javax.annotation.Generated;

import joindb.jooq.public_.tables.AreaImovelJuntos;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.area_imovel_juntos</code>.
     */
    public static final AreaImovelJuntos AREA_IMOVEL_JUNTOS = joindb.jooq.public_.tables.AreaImovelJuntos.AREA_IMOVEL_JUNTOS;
}
