/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.proposta;


import javax.annotation.Generated;

import joindb.jooq.csr_database.tables.records.EstadosRecord;
import joindb.jooq.csr_database.tables.records.MunicipiosRecord;
import joindb.jooq.proposta.tables.GuiaTransitoAnimal;
import joindb.jooq.proposta.tables.Propriedade;
import joindb.jooq.proposta.tables.PropriedadeInformacao;
import joindb.jooq.proposta.tables.records.GuiaTransitoAnimalRecord;
import joindb.jooq.proposta.tables.records.PropriedadeInformacaoRecord;
import joindb.jooq.proposta.tables.records.PropriedadeRecord;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>proposta</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GuiaTransitoAnimalRecord> GTA_PK = UniqueKeys0.GTA_PK;
    public static final UniqueKey<PropriedadeRecord> PROPRIEDADE_PK = UniqueKeys0.PROPRIEDADE_PK;
    public static final UniqueKey<PropriedadeRecord> UQ_PROPRIEDADE_GEOM = UniqueKeys0.UQ_PROPRIEDADE_GEOM;
    public static final UniqueKey<PropriedadeInformacaoRecord> PROPRIEDADE_INFORMATION_PK = UniqueKeys0.PROPRIEDADE_INFORMATION_PK;
    public static final UniqueKey<PropriedadeInformacaoRecord> UQ_PROPRIEDADE_INFORMATION_CNJP_CPF_NOME = UniqueKeys0.UQ_PROPRIEDADE_INFORMATION_CNJP_CPF_NOME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GuiaTransitoAnimalRecord, MunicipiosRecord> GUIA_TRANSITO_ANIMAL__FK_GTA_MUNICIPIO_DESTINO_ID = ForeignKeys0.GUIA_TRANSITO_ANIMAL__FK_GTA_MUNICIPIO_DESTINO_ID;
    public static final ForeignKey<GuiaTransitoAnimalRecord, MunicipiosRecord> GUIA_TRANSITO_ANIMAL__FK_GTA_MUNICIPIO_FONTE_ID = ForeignKeys0.GUIA_TRANSITO_ANIMAL__FK_GTA_MUNICIPIO_FONTE_ID;
    public static final ForeignKey<GuiaTransitoAnimalRecord, EstadosRecord> GUIA_TRANSITO_ANIMAL__FK_GTA_ESTADOS_FONTE_ID = ForeignKeys0.GUIA_TRANSITO_ANIMAL__FK_GTA_ESTADOS_FONTE_ID;
    public static final ForeignKey<GuiaTransitoAnimalRecord, EstadosRecord> GUIA_TRANSITO_ANIMAL__FK_GTA_ESTADOS_DESTINO_ID = ForeignKeys0.GUIA_TRANSITO_ANIMAL__FK_GTA_ESTADOS_DESTINO_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<GuiaTransitoAnimalRecord> GTA_PK = Internal.createUniqueKey(GuiaTransitoAnimal.GUIA_TRANSITO_ANIMAL, "GTA_pk", GuiaTransitoAnimal.GUIA_TRANSITO_ANIMAL.ID);
        public static final UniqueKey<PropriedadeRecord> PROPRIEDADE_PK = Internal.createUniqueKey(Propriedade.PROPRIEDADE, "propriedade_pk", Propriedade.PROPRIEDADE.ID);
        public static final UniqueKey<PropriedadeRecord> UQ_PROPRIEDADE_GEOM = Internal.createUniqueKey(Propriedade.PROPRIEDADE, "uq_propriedade_geom", Propriedade.PROPRIEDADE.GEOM);
        public static final UniqueKey<PropriedadeInformacaoRecord> PROPRIEDADE_INFORMATION_PK = Internal.createUniqueKey(PropriedadeInformacao.PROPRIEDADE_INFORMACAO, "propriedade_information_pk", PropriedadeInformacao.PROPRIEDADE_INFORMACAO.ID);
        public static final UniqueKey<PropriedadeInformacaoRecord> UQ_PROPRIEDADE_INFORMATION_CNJP_CPF_NOME = Internal.createUniqueKey(PropriedadeInformacao.PROPRIEDADE_INFORMACAO, "uq_propriedade_information_cnjp_cpf_nome", PropriedadeInformacao.PROPRIEDADE_INFORMACAO.CNPJ, PropriedadeInformacao.PROPRIEDADE_INFORMACAO.NOME_PROPRIEDADE, PropriedadeInformacao.PROPRIEDADE_INFORMACAO.CPF, PropriedadeInformacao.PROPRIEDADE_INFORMACAO.NOME_PROPRIETARIO, PropriedadeInformacao.PROPRIEDADE_INFORMACAO.PROPRIEDADE_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<GuiaTransitoAnimalRecord, MunicipiosRecord> GUIA_TRANSITO_ANIMAL__FK_GTA_MUNICIPIO_DESTINO_ID = Internal.createForeignKey(joindb.jooq.csr_database.Keys.MUNICIPIOS_PKEY, GuiaTransitoAnimal.GUIA_TRANSITO_ANIMAL, "guia_transito_animal__fk_gta_municipio_destino_id", GuiaTransitoAnimal.GUIA_TRANSITO_ANIMAL.MUNICIPIO_DESTINO);
        public static final ForeignKey<GuiaTransitoAnimalRecord, MunicipiosRecord> GUIA_TRANSITO_ANIMAL__FK_GTA_MUNICIPIO_FONTE_ID = Internal.createForeignKey(joindb.jooq.csr_database.Keys.MUNICIPIOS_PKEY, GuiaTransitoAnimal.GUIA_TRANSITO_ANIMAL, "guia_transito_animal__fk_gta_municipio_fonte_id", GuiaTransitoAnimal.GUIA_TRANSITO_ANIMAL.MUNICIPIO_FONTE);
        public static final ForeignKey<GuiaTransitoAnimalRecord, EstadosRecord> GUIA_TRANSITO_ANIMAL__FK_GTA_ESTADOS_FONTE_ID = Internal.createForeignKey(joindb.jooq.csr_database.Keys.ESTADOS_PKEY, GuiaTransitoAnimal.GUIA_TRANSITO_ANIMAL, "guia_transito_animal__fk_gta_estados_fonte_id", GuiaTransitoAnimal.GUIA_TRANSITO_ANIMAL.ESTADO_FONTE);
        public static final ForeignKey<GuiaTransitoAnimalRecord, EstadosRecord> GUIA_TRANSITO_ANIMAL__FK_GTA_ESTADOS_DESTINO_ID = Internal.createForeignKey(joindb.jooq.csr_database.Keys.ESTADOS_PKEY, GuiaTransitoAnimal.GUIA_TRANSITO_ANIMAL, "guia_transito_animal__fk_gta_estados_destino_id", GuiaTransitoAnimal.GUIA_TRANSITO_ANIMAL.ESTADO_DESTINO);
    }
}
