/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.proposta;


import java.math.BigDecimal;

import javax.annotation.Generated;

import joindb.jooq.proposta.routines.Getanimalidade;
import joindb.jooq.proposta.routines.Getcpfcnpjvalidity;
import joindb.jooq.proposta.routines.Getequality;
import joindb.jooq.proposta.routines.Getinfocodimovel;
import joindb.jooq.proposta.routines.Validcpfcnpjornull;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in proposta
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>proposta.getanimalidade</code>
     */
    public static Getanimalidade getanimalidade(Configuration configuration, String attributedescription, String animaltype) {
        Getanimalidade p = new Getanimalidade();
        p.setAttributedescription(attributedescription);
        p.setAnimaltype(animaltype);

        p.execute(configuration);
        return p;
    }

    /**
     * Call <code>proposta.getCpfCnpjValidity</code>
     */
    public static Integer getcpfcnpjvalidity(Configuration configuration, BigDecimal value) {
        Getcpfcnpjvalidity f = new Getcpfcnpjvalidity();
        f.setValue(value);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>proposta.getCpfCnpjValidity</code> as a field.
     */
    public static Field<Integer> getcpfcnpjvalidity(BigDecimal value) {
        Getcpfcnpjvalidity f = new Getcpfcnpjvalidity();
        f.setValue(value);

        return f.asField();
    }

    /**
     * Get <code>proposta.getCpfCnpjValidity</code> as a field.
     */
    public static Field<Integer> getcpfcnpjvalidity(Field<BigDecimal> value) {
        Getcpfcnpjvalidity f = new Getcpfcnpjvalidity();
        f.setValue(value);

        return f.asField();
    }

    /**
     * Call <code>proposta.getequality</code>
     */
    public static Float getequality(Configuration configuration, String text1, String text2) {
        Getequality f = new Getequality();
        f.setText1(text1);
        f.setText2(text2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>proposta.getequality</code> as a field.
     */
    public static Field<Float> getequality(String text1, String text2) {
        Getequality f = new Getequality();
        f.setText1(text1);
        f.setText2(text2);

        return f.asField();
    }

    /**
     * Get <code>proposta.getequality</code> as a field.
     */
    public static Field<Float> getequality(Field<String> text1, Field<String> text2) {
        Getequality f = new Getequality();
        f.setText1(text1);
        f.setText2(text2);

        return f.asField();
    }

    /**
     * Call <code>proposta.getinfocodimovel</code>
     */
    public static Getinfocodimovel getinfocodimovel(Configuration configuration, String codigoimovel) {
        Getinfocodimovel p = new Getinfocodimovel();
        p.setCodigoimovel(codigoimovel);

        p.execute(configuration);
        return p;
    }

    /**
     * Call <code>proposta.validcpfcnpjornull</code>
     */
    public static BigDecimal validcpfcnpjornull(Configuration configuration, BigDecimal value, Boolean iscpf) {
        Validcpfcnpjornull f = new Validcpfcnpjornull();
        f.setValue(value);
        f.setIscpf(iscpf);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>proposta.validcpfcnpjornull</code> as a field.
     */
    public static Field<BigDecimal> validcpfcnpjornull(BigDecimal value, Boolean iscpf) {
        Validcpfcnpjornull f = new Validcpfcnpjornull();
        f.setValue(value);
        f.setIscpf(iscpf);

        return f.asField();
    }

    /**
     * Get <code>proposta.validcpfcnpjornull</code> as a field.
     */
    public static Field<BigDecimal> validcpfcnpjornull(Field<BigDecimal> value, Field<Boolean> iscpf) {
        Validcpfcnpjornull f = new Validcpfcnpjornull();
        f.setValue(value);
        f.setIscpf(iscpf);

        return f.asField();
    }
}
