/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.csr_database;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import joindb.jooq.DefaultCatalog;
import joindb.jooq.csr_database.tables.Estados;
import joindb.jooq.csr_database.tables.MtMunicipio;
import joindb.jooq.csr_database.tables.Municipios;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CsrDatabase extends SchemaImpl {

    private static final long serialVersionUID = -1460017638;

    /**
     * The reference instance of <code>csr_database</code>
     */
    public static final CsrDatabase CSR_DATABASE = new CsrDatabase();

    /**
     * The table <code>csr_database.estados</code>.
     */
    public final Estados ESTADOS = joindb.jooq.csr_database.tables.Estados.ESTADOS;

    /**
     * The table <code>csr_database.mt_municipio</code>.
     */
    public final MtMunicipio MT_MUNICIPIO = joindb.jooq.csr_database.tables.MtMunicipio.MT_MUNICIPIO;

    /**
     * The table <code>csr_database.municipios</code>.
     */
    public final Municipios MUNICIPIOS = joindb.jooq.csr_database.tables.Municipios.MUNICIPIOS;

    /**
     * No further instances allowed
     */
    private CsrDatabase() {
        super("csr_database", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ESTADOS_ID_SEQ,
            Sequences.MUNICIPIOS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Estados.ESTADOS,
            MtMunicipio.MT_MUNICIPIO,
            Municipios.MUNICIPIOS);
    }
}
