/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.csr_database;


import javax.annotation.Generated;

import joindb.jooq.csr_database.tables.Estados;
import joindb.jooq.csr_database.tables.Municipios;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>csr_database</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ESTADOS_PKEY = Indexes0.ESTADOS_PKEY;
    public static final Index MUNICIPIOS_PKEY = Indexes0.MUNICIPIOS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ESTADOS_PKEY = Internal.createIndex("estados_pkey", Estados.ESTADOS, new OrderField[] { Estados.ESTADOS.ID }, true);
        public static Index MUNICIPIOS_PKEY = Internal.createIndex("municipios_pkey", Municipios.MUNICIPIOS, new OrderField[] { Municipios.MUNICIPIOS.ID }, true);
    }
}
