/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.csr_database;


import javax.annotation.Generated;

import joindb.jooq.csr_database.tables.Estados;
import joindb.jooq.csr_database.tables.Municipios;
import joindb.jooq.csr_database.tables.records.EstadosRecord;
import joindb.jooq.csr_database.tables.records.MunicipiosRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>csr_database</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EstadosRecord, Integer> IDENTITY_ESTADOS = Identities0.IDENTITY_ESTADOS;
    public static final Identity<MunicipiosRecord, Integer> IDENTITY_MUNICIPIOS = Identities0.IDENTITY_MUNICIPIOS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EstadosRecord> ESTADOS_PKEY = UniqueKeys0.ESTADOS_PKEY;
    public static final UniqueKey<MunicipiosRecord> MUNICIPIOS_PKEY = UniqueKeys0.MUNICIPIOS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<EstadosRecord, Integer> IDENTITY_ESTADOS = Internal.createIdentity(Estados.ESTADOS, Estados.ESTADOS.ID);
        public static Identity<MunicipiosRecord, Integer> IDENTITY_MUNICIPIOS = Internal.createIdentity(Municipios.MUNICIPIOS, Municipios.MUNICIPIOS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<EstadosRecord> ESTADOS_PKEY = Internal.createUniqueKey(Estados.ESTADOS, "estados_pkey", Estados.ESTADOS.ID);
        public static final UniqueKey<MunicipiosRecord> MUNICIPIOS_PKEY = Internal.createUniqueKey(Municipios.MUNICIPIOS, "municipios_pkey", Municipios.MUNICIPIOS.ID);
    }
}
