/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.csr_database;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in csr_database
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>csr_database.estados_id_seq</code>
     */
    public static final Sequence<Integer> ESTADOS_ID_SEQ = new SequenceImpl<Integer>("estados_id_seq", CsrDatabase.CSR_DATABASE, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>csr_database.municipios_id_seq</code>
     */
    public static final Sequence<Integer> MUNICIPIOS_ID_SEQ = new SequenceImpl<Integer>("municipios_id_seq", CsrDatabase.CSR_DATABASE, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
