/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.csr_database;


import javax.annotation.Generated;

import joindb.jooq.csr_database.tables.Estados;
import joindb.jooq.csr_database.tables.MtMunicipio;
import joindb.jooq.csr_database.tables.Municipios;


/**
 * Convenience access to all tables in csr_database
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>csr_database.estados</code>.
     */
    public static final Estados ESTADOS = joindb.jooq.csr_database.tables.Estados.ESTADOS;

    /**
     * The table <code>csr_database.mt_municipio</code>.
     */
    public static final MtMunicipio MT_MUNICIPIO = joindb.jooq.csr_database.tables.MtMunicipio.MT_MUNICIPIO;

    /**
     * The table <code>csr_database.municipios</code>.
     */
    public static final Municipios MUNICIPIOS = joindb.jooq.csr_database.tables.Municipios.MUNICIPIOS;
}
