/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.fbds;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import joindb.jooq.DefaultCatalog;
import joindb.jooq.fbds.tables.AreaImovelMgEs_228Muni;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fbds extends SchemaImpl {

    private static final long serialVersionUID = -1490007964;

    /**
     * The reference instance of <code>FBDS</code>
     */
    public static final Fbds FBDS = new Fbds();

    /**
     * The table <code>FBDS.area_imovel_mg_es_228_muni</code>.
     */
    public final AreaImovelMgEs_228Muni AREA_IMOVEL_MG_ES_228_MUNI = joindb.jooq.fbds.tables.AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI;

    /**
     * No further instances allowed
     */
    private Fbds() {
        super("FBDS", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.AREA_IMOVEL_MG_ES_228_MUNI_ID_0_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI);
    }
}
