/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.fbds;


import javax.annotation.Generated;

import joindb.jooq.fbds.tables.AreaImovelMgEs_228Muni;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>FBDS</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AREA_IMOVEL_MG_ES_228_MUNI_PKEY = Indexes0.AREA_IMOVEL_MG_ES_228_MUNI_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AREA_IMOVEL_MG_ES_228_MUNI_PKEY = Internal.createIndex("area_imovel_mg_es_228_muni_pkey", AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI, new OrderField[] { AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI.ID_0 }, true);
    }
}
