/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.fbds;


import javax.annotation.Generated;

import joindb.jooq.fbds.tables.AreaImovelMgEs_228Muni;


/**
 * Convenience access to all tables in FBDS
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>FBDS.area_imovel_mg_es_228_muni</code>.
     */
    public static final AreaImovelMgEs_228Muni AREA_IMOVEL_MG_ES_228_MUNI = joindb.jooq.fbds.tables.AreaImovelMgEs_228Muni.AREA_IMOVEL_MG_ES_228_MUNI;
}
