/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.lt_model;


import javax.annotation.Generated;

import joindb.jooq.lt_model.tables.ResultRandom;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>lt_model</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GIX_RESULT_RANDOM = Indexes0.GIX_RESULT_RANDOM;
    public static final Index RESULT_PKEY3 = Indexes0.RESULT_PKEY3;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index GIX_RESULT_RANDOM = Internal.createIndex("gix_result_random", ResultRandom.RESULT_RANDOM, new OrderField[] { ResultRandom.RESULT_RANDOM.GEOM }, false);
        public static Index RESULT_PKEY3 = Internal.createIndex("result_pkey3", ResultRandom.RESULT_RANDOM, new OrderField[] { ResultRandom.RESULT_RANDOM.GID }, true);
    }
}
