/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.lt_model;


import javax.annotation.Generated;

import joindb.jooq.lt_model.tables.ResultRandom;
import joindb.jooq.lt_model.tables.records.ResultRandomRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>lt_model</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ResultRandomRecord, Integer> IDENTITY_RESULT_RANDOM = Identities0.IDENTITY_RESULT_RANDOM;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ResultRandomRecord> RESULT_PKEY3 = UniqueKeys0.RESULT_PKEY3;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ResultRandomRecord, Integer> IDENTITY_RESULT_RANDOM = Internal.createIdentity(ResultRandom.RESULT_RANDOM, ResultRandom.RESULT_RANDOM.GID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ResultRandomRecord> RESULT_PKEY3 = Internal.createUniqueKey(ResultRandom.RESULT_RANDOM, "result_pkey3", ResultRandom.RESULT_RANDOM.GID);
    }
}
