/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.lt_model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import joindb.jooq.DefaultCatalog;
import joindb.jooq.lt_model.tables.ResultRandom;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LtModel extends SchemaImpl {

    private static final long serialVersionUID = -1076652434;

    /**
     * The reference instance of <code>lt_model</code>
     */
    public static final LtModel LT_MODEL = new LtModel();

    /**
     * The table <code>lt_model.result_random</code>.
     */
    public final ResultRandom RESULT_RANDOM = joindb.jooq.lt_model.tables.ResultRandom.RESULT_RANDOM;

    /**
     * No further instances allowed
     */
    private LtModel() {
        super("lt_model", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.RESULT_GID_SEQ3);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ResultRandom.RESULT_RANDOM);
    }
}
