/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.lt_model;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in lt_model
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>lt_model.result_gid_seq3</code>
     */
    public static final Sequence<Integer> RESULT_GID_SEQ3 = new SequenceImpl<Integer>("result_gid_seq3", LtModel.LT_MODEL, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
