/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.lt_model;


import javax.annotation.Generated;

import joindb.jooq.lt_model.tables.ResultRandom;


/**
 * Convenience access to all tables in lt_model
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>lt_model.result_random</code>.
     */
    public static final ResultRandom RESULT_RANDOM = joindb.jooq.lt_model.tables.ResultRandom.RESULT_RANDOM;
}
