/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.csr_database.tables.records;


import javax.annotation.Generated;

import joindb.jooq.csr_database.tables.MtMunicipio;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MtMunicipioRecord extends TableRecordImpl<MtMunicipioRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 624275590;

    /**
     * Setter for <code>csr_database.mt_municipio.estado_id</code>.
     */
    public void setEstadoId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>csr_database.mt_municipio.estado_id</code>.
     */
    public Integer getEstadoId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>csr_database.mt_municipio.estado_sigla</code>.
     */
    public void setEstadoSigla(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>csr_database.mt_municipio.estado_sigla</code>.
     */
    public String getEstadoSigla() {
        return (String) get(1);
    }

    /**
     * Setter for <code>csr_database.mt_municipio.municipio_id</code>.
     */
    public void setMunicipioId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>csr_database.mt_municipio.municipio_id</code>.
     */
    public Integer getMunicipioId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>csr_database.mt_municipio.municipio_geocodigo</code>.
     */
    public void setMunicipioGeocodigo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>csr_database.mt_municipio.municipio_geocodigo</code>.
     */
    public Integer getMunicipioGeocodigo() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MtMunicipio.MT_MUNICIPIO.ESTADO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MtMunicipio.MT_MUNICIPIO.ESTADO_SIGLA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MtMunicipio.MT_MUNICIPIO.MUNICIPIO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MtMunicipio.MT_MUNICIPIO.MUNICIPIO_GEOCODIGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getEstadoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEstadoSigla();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMunicipioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getMunicipioGeocodigo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEstadoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEstadoSigla();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMunicipioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMunicipioGeocodigo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MtMunicipioRecord value1(Integer value) {
        setEstadoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MtMunicipioRecord value2(String value) {
        setEstadoSigla(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MtMunicipioRecord value3(Integer value) {
        setMunicipioId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MtMunicipioRecord value4(Integer value) {
        setMunicipioGeocodigo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MtMunicipioRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MtMunicipioRecord
     */
    public MtMunicipioRecord() {
        super(MtMunicipio.MT_MUNICIPIO);
    }

    /**
     * Create a detached, initialised MtMunicipioRecord
     */
    public MtMunicipioRecord(Integer estadoId, String estadoSigla, Integer municipioId, Integer municipioGeocodigo) {
        super(MtMunicipio.MT_MUNICIPIO);

        set(0, estadoId);
        set(1, estadoSigla);
        set(2, municipioId);
        set(3, municipioGeocodigo);
    }
}
