/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.csr_database.tables.records;


import javax.annotation.Generated;

import joindb.jooq.csr_database.tables.Municipios;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.postgis.Geometry;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MunicipiosRecord extends UpdatableRecordImpl<MunicipiosRecord> implements Record4<Integer, Geometry, String, Integer> {

    private static final long serialVersionUID = 1633099066;

    /**
     * Setter for <code>csr_database.municipios.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>csr_database.municipios.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>csr_database.municipios.geom</code>.
     */
    public void setGeom(Geometry value) {
        set(1, value);
    }

    /**
     * Getter for <code>csr_database.municipios.geom</code>.
     */
    public Geometry getGeom() {
        return (Geometry) get(1);
    }

    /**
     * Setter for <code>csr_database.municipios.nome</code>.
     */
    public void setNome(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>csr_database.municipios.nome</code>.
     */
    public String getNome() {
        return (String) get(2);
    }

    /**
     * Setter for <code>csr_database.municipios.geocodigo</code>.
     */
    public void setGeocodigo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>csr_database.municipios.geocodigo</code>.
     */
    public Integer getGeocodigo() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Geometry, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Geometry, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Municipios.MUNICIPIOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Geometry> field2() {
        return Municipios.MUNICIPIOS.GEOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Municipios.MUNICIPIOS.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Municipios.MUNICIPIOS.GEOCODIGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Geometry component2() {
        return getGeom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getGeocodigo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Geometry value2() {
        return getGeom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGeocodigo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MunicipiosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MunicipiosRecord value2(Geometry value) {
        setGeom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MunicipiosRecord value3(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MunicipiosRecord value4(Integer value) {
        setGeocodigo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MunicipiosRecord values(Integer value1, Geometry value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MunicipiosRecord
     */
    public MunicipiosRecord() {
        super(Municipios.MUNICIPIOS);
    }

    /**
     * Create a detached, initialised MunicipiosRecord
     */
    public MunicipiosRecord(Integer id, Geometry geom, String nome, Integer geocodigo) {
        super(Municipios.MUNICIPIOS);

        set(0, id);
        set(1, geom);
        set(2, nome);
        set(3, geocodigo);
    }
}
