/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.lt_model.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import joindb.jooq.lt_model.tables.ResultRandom;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.postgis.Geometry;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResultRandomRecord extends UpdatableRecordImpl<ResultRandomRecord> {

    private static final long serialVersionUID = -894211777;

    /**
     * Setter for <code>lt_model.result_random.gid</code>.
     */
    public void setGid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lt_model.result_random.gid</code>.
     */
    public Integer getGid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lt_model.result_random.table_source</code>.
     */
    public void setTableSource(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lt_model.result_random.table_source</code>.
     */
    public String getTableSource() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lt_model.result_random.ownership_class</code>.
     */
    public void setOwnershipClass(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lt_model.result_random.ownership_class</code>.
     */
    public String getOwnershipClass() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lt_model.result_random.sub_class</code>.
     */
    public void setSubClass(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lt_model.result_random.sub_class</code>.
     */
    public String getSubClass() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lt_model.result_random.area_original</code>.
     */
    public void setAreaOriginal(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>lt_model.result_random.area_original</code>.
     */
    public BigDecimal getAreaOriginal() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>lt_model.result_random.original_gid</code>.
     */
    public void setOriginalGid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>lt_model.result_random.original_gid</code>.
     */
    public Long getOriginalGid() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>lt_model.result_random.geom</code>.
     */
    public void setGeom(Geometry value) {
        set(6, value);
    }

    /**
     * Getter for <code>lt_model.result_random.geom</code>.
     */
    public Geometry getGeom() {
        return (Geometry) get(6);
    }

    /**
     * Setter for <code>lt_model.result_random.area</code>.
     */
    public void setArea(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>lt_model.result_random.area</code>.
     */
    public BigDecimal getArea() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>lt_model.result_random.ag_area_loss</code>.
     */
    public void setAgAreaLoss(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>lt_model.result_random.ag_area_loss</code>.
     */
    public BigDecimal getAgAreaLoss() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>lt_model.result_random.aru_area_loss</code>.
     */
    public void setAruAreaLoss(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>lt_model.result_random.aru_area_loss</code>.
     */
    public BigDecimal getAruAreaLoss() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>lt_model.result_random.carpo_area_loss</code>.
     */
    public void setCarpoAreaLoss(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>lt_model.result_random.carpo_area_loss</code>.
     */
    public BigDecimal getCarpoAreaLoss() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>lt_model.result_random.carpr_area_loss</code>.
     */
    public void setCarprAreaLoss(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>lt_model.result_random.carpr_area_loss</code>.
     */
    public BigDecimal getCarprAreaLoss() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>lt_model.result_random.com_area_loss</code>.
     */
    public void setComAreaLoss(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>lt_model.result_random.com_area_loss</code>.
     */
    public BigDecimal getComAreaLoss() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>lt_model.result_random.ml_area_loss</code>.
     */
    public void setMlAreaLoss(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>lt_model.result_random.ml_area_loss</code>.
     */
    public BigDecimal getMlAreaLoss() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>lt_model.result_random.nd_b_area_loss</code>.
     */
    public void setNdBAreaLoss(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>lt_model.result_random.nd_b_area_loss</code>.
     */
    public BigDecimal getNdBAreaLoss() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>lt_model.result_random.nd_i_area_loss</code>.
     */
    public void setNdIAreaLoss(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>lt_model.result_random.nd_i_area_loss</code>.
     */
    public BigDecimal getNdIAreaLoss() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>lt_model.result_random.ql_area_loss</code>.
     */
    public void setQlAreaLoss(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>lt_model.result_random.ql_area_loss</code>.
     */
    public BigDecimal getQlAreaLoss() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>lt_model.result_random.sigef_area_loss</code>.
     */
    public void setSigefAreaLoss(BigDecimal value) {
        set(17, value);
    }

    /**
     * Getter for <code>lt_model.result_random.sigef_area_loss</code>.
     */
    public BigDecimal getSigefAreaLoss() {
        return (BigDecimal) get(17);
    }

    /**
     * Setter for <code>lt_model.result_random.ti_h_area_loss</code>.
     */
    public void setTiHAreaLoss(BigDecimal value) {
        set(18, value);
    }

    /**
     * Getter for <code>lt_model.result_random.ti_h_area_loss</code>.
     */
    public BigDecimal getTiHAreaLoss() {
        return (BigDecimal) get(18);
    }

    /**
     * Setter for <code>lt_model.result_random.ti_n_area_loss</code>.
     */
    public void setTiNAreaLoss(BigDecimal value) {
        set(19, value);
    }

    /**
     * Getter for <code>lt_model.result_random.ti_n_area_loss</code>.
     */
    public BigDecimal getTiNAreaLoss() {
        return (BigDecimal) get(19);
    }

    /**
     * Setter for <code>lt_model.result_random.tlpc_area_loss</code>.
     */
    public void setTlpcAreaLoss(BigDecimal value) {
        set(20, value);
    }

    /**
     * Getter for <code>lt_model.result_random.tlpc_area_loss</code>.
     */
    public BigDecimal getTlpcAreaLoss() {
        return (BigDecimal) get(20);
    }

    /**
     * Setter for <code>lt_model.result_random.tlpl_area_loss</code>.
     */
    public void setTlplAreaLoss(BigDecimal value) {
        set(21, value);
    }

    /**
     * Getter for <code>lt_model.result_random.tlpl_area_loss</code>.
     */
    public BigDecimal getTlplAreaLoss() {
        return (BigDecimal) get(21);
    }

    /**
     * Setter for <code>lt_model.result_random.trans_area_loss</code>.
     */
    public void setTransAreaLoss(BigDecimal value) {
        set(22, value);
    }

    /**
     * Getter for <code>lt_model.result_random.trans_area_loss</code>.
     */
    public BigDecimal getTransAreaLoss() {
        return (BigDecimal) get(22);
    }

    /**
     * Setter for <code>lt_model.result_random.ucpi_area_loss</code>.
     */
    public void setUcpiAreaLoss(BigDecimal value) {
        set(23, value);
    }

    /**
     * Getter for <code>lt_model.result_random.ucpi_area_loss</code>.
     */
    public BigDecimal getUcpiAreaLoss() {
        return (BigDecimal) get(23);
    }

    /**
     * Setter for <code>lt_model.result_random.ucus_area_loss</code>.
     */
    public void setUcusAreaLoss(BigDecimal value) {
        set(24, value);
    }

    /**
     * Getter for <code>lt_model.result_random.ucus_area_loss</code>.
     */
    public BigDecimal getUcusAreaLoss() {
        return (BigDecimal) get(24);
    }

    /**
     * Setter for <code>lt_model.result_random.urb_area_loss</code>.
     */
    public void setUrbAreaLoss(BigDecimal value) {
        set(25, value);
    }

    /**
     * Getter for <code>lt_model.result_random.urb_area_loss</code>.
     */
    public BigDecimal getUrbAreaLoss() {
        return (BigDecimal) get(25);
    }

    /**
     * Setter for <code>lt_model.result_random.cd_mun_2006</code>.
     */
    public void setCdMun_2006(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>lt_model.result_random.cd_mun_2006</code>.
     */
    public Integer getCdMun_2006() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>lt_model.result_random.rast</code>.
     */
    public void setRast(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>lt_model.result_random.rast</code>.
     */
    public Integer getRast() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>lt_model.result_random.name</code>.
     */
    public void setName(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>lt_model.result_random.name</code>.
     */
    public String getName() {
        return (String) get(28);
    }

    /**
     * Setter for <code>lt_model.result_random.cd_mun</code>.
     */
    public void setCdMun(Integer value) {
        set(29, value);
    }

    /**
     * Getter for <code>lt_model.result_random.cd_mun</code>.
     */
    public Integer getCdMun() {
        return (Integer) get(29);
    }

    /**
     * Setter for <code>lt_model.result_random.cd_mun_contain</code>.
     */
    public void setCdMunContain(Boolean value) {
        set(30, value);
    }

    /**
     * Getter for <code>lt_model.result_random.cd_mun_contain</code>.
     */
    public Boolean getCdMunContain() {
        return (Boolean) get(30);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResultRandomRecord
     */
    public ResultRandomRecord() {
        super(ResultRandom.RESULT_RANDOM);
    }

    /**
     * Create a detached, initialised ResultRandomRecord
     */
    public ResultRandomRecord(Integer gid, String tableSource, String ownershipClass, String subClass, BigDecimal areaOriginal, Long originalGid, Geometry geom, BigDecimal area, BigDecimal agAreaLoss, BigDecimal aruAreaLoss, BigDecimal carpoAreaLoss, BigDecimal carprAreaLoss, BigDecimal comAreaLoss, BigDecimal mlAreaLoss, BigDecimal ndBAreaLoss, BigDecimal ndIAreaLoss, BigDecimal qlAreaLoss, BigDecimal sigefAreaLoss, BigDecimal tiHAreaLoss, BigDecimal tiNAreaLoss, BigDecimal tlpcAreaLoss, BigDecimal tlplAreaLoss, BigDecimal transAreaLoss, BigDecimal ucpiAreaLoss, BigDecimal ucusAreaLoss, BigDecimal urbAreaLoss, Integer cdMun_2006, Integer rast, String name, Integer cdMun, Boolean cdMunContain) {
        super(ResultRandom.RESULT_RANDOM);

        set(0, gid);
        set(1, tableSource);
        set(2, ownershipClass);
        set(3, subClass);
        set(4, areaOriginal);
        set(5, originalGid);
        set(6, geom);
        set(7, area);
        set(8, agAreaLoss);
        set(9, aruAreaLoss);
        set(10, carpoAreaLoss);
        set(11, carprAreaLoss);
        set(12, comAreaLoss);
        set(13, mlAreaLoss);
        set(14, ndBAreaLoss);
        set(15, ndIAreaLoss);
        set(16, qlAreaLoss);
        set(17, sigefAreaLoss);
        set(18, tiHAreaLoss);
        set(19, tiNAreaLoss);
        set(20, tlpcAreaLoss);
        set(21, tlplAreaLoss);
        set(22, transAreaLoss);
        set(23, ucpiAreaLoss);
        set(24, ucusAreaLoss);
        set(25, urbAreaLoss);
        set(26, cdMun_2006);
        set(27, rast);
        set(28, name);
        set(29, cdMun);
        set(30, cdMunContain);
    }
}
