/*
 * This file is generated by jOOQ.
 */
package joindb.jooq.public_.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import joindb.jooq.public_.tables.AreaImovelJuntos;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.postgis.Geometry;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AreaImovelJuntosRecord extends UpdatableRecordImpl<AreaImovelJuntosRecord> implements Record10<Integer, Geometry, String, BigDecimal, String, String, BigDecimal, String, String, String> {

    private static final long serialVersionUID = 470313467;

    /**
     * Setter for <code>public.area_imovel_juntos.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.area_imovel_juntos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.area_imovel_juntos.geom</code>.
     */
    public void setGeom(Geometry value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.area_imovel_juntos.geom</code>.
     */
    public Geometry getGeom() {
        return (Geometry) get(1);
    }

    /**
     * Setter for <code>public.area_imovel_juntos.cod_imovel</code>.
     */
    public void setCodImovel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.area_imovel_juntos.cod_imovel</code>.
     */
    public String getCodImovel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.area_imovel_juntos.num_area</code>.
     */
    public void setNumArea(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.area_imovel_juntos.num_area</code>.
     */
    public BigDecimal getNumArea() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.area_imovel_juntos.cod_estado</code>.
     */
    public void setCodEstado(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.area_imovel_juntos.cod_estado</code>.
     */
    public String getCodEstado() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.area_imovel_juntos.nom_munici</code>.
     */
    public void setNomMunici(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.area_imovel_juntos.nom_munici</code>.
     */
    public String getNomMunici() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.area_imovel_juntos.num_modulo</code>.
     */
    public void setNumModulo(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.area_imovel_juntos.num_modulo</code>.
     */
    public BigDecimal getNumModulo() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.area_imovel_juntos.tipo_imove</code>.
     */
    public void setTipoImove(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.area_imovel_juntos.tipo_imove</code>.
     */
    public String getTipoImove() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.area_imovel_juntos.situacao</code>.
     */
    public void setSituacao(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.area_imovel_juntos.situacao</code>.
     */
    public String getSituacao() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.area_imovel_juntos.condicao_i</code>.
     */
    public void setCondicaoI(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.area_imovel_juntos.condicao_i</code>.
     */
    public String getCondicaoI() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Geometry, String, BigDecimal, String, String, BigDecimal, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Geometry, String, BigDecimal, String, String, BigDecimal, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AreaImovelJuntos.AREA_IMOVEL_JUNTOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Geometry> field2() {
        return AreaImovelJuntos.AREA_IMOVEL_JUNTOS.GEOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AreaImovelJuntos.AREA_IMOVEL_JUNTOS.COD_IMOVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return AreaImovelJuntos.AREA_IMOVEL_JUNTOS.NUM_AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AreaImovelJuntos.AREA_IMOVEL_JUNTOS.COD_ESTADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return AreaImovelJuntos.AREA_IMOVEL_JUNTOS.NOM_MUNICI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return AreaImovelJuntos.AREA_IMOVEL_JUNTOS.NUM_MODULO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return AreaImovelJuntos.AREA_IMOVEL_JUNTOS.TIPO_IMOVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return AreaImovelJuntos.AREA_IMOVEL_JUNTOS.SITUACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return AreaImovelJuntos.AREA_IMOVEL_JUNTOS.CONDICAO_I;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Geometry component2() {
        return getGeom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCodImovel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getNumArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCodEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNomMunici();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getNumModulo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getTipoImove();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getSituacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCondicaoI();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Geometry value2() {
        return getGeom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCodImovel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getNumArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCodEstado();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNomMunici();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getNumModulo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTipoImove();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSituacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCondicaoI();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord value2(Geometry value) {
        setGeom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord value3(String value) {
        setCodImovel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord value4(BigDecimal value) {
        setNumArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord value5(String value) {
        setCodEstado(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord value6(String value) {
        setNomMunici(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord value7(BigDecimal value) {
        setNumModulo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord value8(String value) {
        setTipoImove(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord value9(String value) {
        setSituacao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord value10(String value) {
        setCondicaoI(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AreaImovelJuntosRecord values(Integer value1, Geometry value2, String value3, BigDecimal value4, String value5, String value6, BigDecimal value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AreaImovelJuntosRecord
     */
    public AreaImovelJuntosRecord() {
        super(AreaImovelJuntos.AREA_IMOVEL_JUNTOS);
    }

    /**
     * Create a detached, initialised AreaImovelJuntosRecord
     */
    public AreaImovelJuntosRecord(Integer id, Geometry geom, String codImovel, BigDecimal numArea, String codEstado, String nomMunici, BigDecimal numModulo, String tipoImove, String situacao, String condicaoI) {
        super(AreaImovelJuntos.AREA_IMOVEL_JUNTOS);

        set(0, id);
        set(1, geom);
        set(2, codImovel);
        set(3, numArea);
        set(4, codEstado);
        set(5, nomMunici);
        set(6, numModulo);
        set(7, tipoImove);
        set(8, situacao);
        set(9, condicaoI);
    }
}
